### ISSUE TITLE
Wrapper over sb-md5 on sbcl / use %byte-blt rather than ub8-bash-copy

### ISSUE THREAD

**Issue by csrhodes** [pmai/md5#3]
Could this please be adjusted to be a thin wrapper over the `sb-md5` contrib when running on SBCL?

The reason is that we changed the checking on the byte-bashing: the high-level byte-bashers now assert (under some circumstances) that they're being called with compatible arguments (and not accessing elements off the end of valid spaces).  This catches https://github.com/pmai/md5/blob/master/md5.lisp#L375.  We've fixed our own sb-md5, and if this were a thin layer then it would automatically work, both now and the next time we break an internal interface...

Alternatively, the fix is to use `%byte-blt` instead of `ub8-bash-copy` in that line.

Thanks!

**Comment by pmai** [comment]
Should be fixed conservatively for now with the new 2.0.5 release. Will investigate switching to sb-md5 wrapper going forward.

Thanks for the heads-up, and CU!
